server:
  port: 8082
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 30m

spring:
  application:
    name: olx-Login
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: olx_login
  security:
    oauth2:
      client:
        registration:
          google: 
            redirect-uri: ${redirect-uri}
            client-id: ${oauth2_client_id}
            client-secret: ${oaut2_client_secret}
          #redirect-url: localhost:8082/login/oauth2/code/google.

management:
  endpoints:
    web:
      base-path: /olxlogin
      exposure:
        include:
          - "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true